version: '3.7'
services:
  api:
    container_name: tcc-api
    restart: always
    depends_on: 
        - mongo
    build: .
    env_file: 
      - ".env/"
    environment:
      - PORT=3333
      - PRODUCTION=dev
      - MONGONAME=youtubeIds
      - BASEAUTHUSERNAME=Rodrigo
      - BASEAUTHPASSWORD=12345
      - COUNTYS=ie,us,ca,br,hr
      - CRONTAB=* * * * *
    ports:
        - "3333:3333"
  mongo:
    container_name: mongo
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
