version: '3'
services:
  api:
    container_name: tcc-api
    restart: always
    depends_on: 
        - mongodb
    build: ./
    ports:
        - "3333:3333"
    links:
        - mongodb
  mongodb:
    container_name: mongo
    image: "mongo"
    restart: always
    ports:
        - "27017:27017"
    